server:
  port: 6060
  #servlet:
    #contextPath: /api/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Asd86587559
    url: jdbc:mysql://localhost:3306/ffast?useUnicode=true&characterEncoding=utf-8&useSSL=false
    druid:
      initialSize: 5
      maxActive: 20
      minIdle: 5
      maxWait: 60000
      transaction-query-timeout: 6000 #事务查询超时时间
      remove-abandoned-timeout: 1800 #关闭空闲连接超时时间
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    enabled: true
    host: 127.0.0.1
    port: 6379
    password: 523344582
    #过期时间（秒）
    expirationSecond: 1800
    #序列号方式 默认0   0:"FastJSON",1:"JackJson",2:"Msgpack"
    serializerType: 2


#日志配置
logging:
  config: classpath:prod/logback.xml

auth:
  pwdDefault: '123456'
  #是否开启验证码
  captchaEnable: true
  #0使用jwt 1使用redis
  type: 1
  #过期时间（秒）
  expirationSecond: 86400
  jwt:
    secret: '75SASD6fad5as6d5sa#ddd42ddd$fdd$d@dd'


#上传配置
upload:
 filesBasePath: '/data/wwwroot/default/files/'
 uploadUrl: 'http://39.107.104.190/files/'


